// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestgroundFour.Models;

#nullable disable

namespace TestgroundFour.Migrations.Clientside
{
    [DbContext(typeof(ClientsideContext))]
    [Migration("20240514055013_FinalDBClientNull")]
    partial class FinalDBClientNull
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TestgroundFour.Models.Clientside", b =>
                {
                    b.Property<string>("Plant")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Unit")
                        .HasColumnType("int");

                    b.Property<string>("Celltype")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Cellno")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Docno")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Process")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Pyorder")
                        .HasColumnType("int");

                    b.Property<string>("Pyno")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Approvercheck")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Approvername")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Check")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pydesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pypurpose")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pytype")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Updatename")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Plant", "Unit", "Celltype", "Cellno", "Model", "Docno", "Process", "Pyorder", "Pyno", "Date");

                    b.ToTable("clientdatas");
                });
#pragma warning restore 612, 618
        }
    }
}
